/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'createdAt' : Time,
  'totalAmount' : number,
  'buyer' : Principal,
  'items' : Array<OrderItem>,
  'farmer' : Principal,
}
export interface OrderItem {
  'productId' : bigint,
  'quantity' : bigint,
  'price' : number,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'fulfilled' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export interface PlatformAnalytics {
  'totalProducts' : bigint,
  'totalOrders' : bigint,
  'totalHomeBuyers' : bigint,
  'totalSuspendedUsers' : bigint,
  'totalBusinessBuyers' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : number,
  'totalFarmers' : bigint,
}
export interface Product {
  'id' : bigint,
  'moderationNote' : [] | [string],
  'moderated' : boolean,
  'imageBlob' : [] | [ExternalBlob],
  'organic' : boolean,
  'name' : string,
  'createdAt' : Time,
  'unit' : ProductUnit,
  'description' : string,
  'available' : boolean,
  'quantity' : bigint,
  'category' : ProductCategory,
  'price' : number,
  'farmer' : Principal,
}
export type ProductCategory = { 'grains' : null } |
  { 'organicFood' : null } |
  { 'others' : null } |
  { 'fruits' : null } |
  { 'vegetables' : null } |
  { 'dairy' : null };
export type ProductUnit = { 'kg' : null } |
  { 'pieces' : null } |
  { 'liters' : null };
export interface RecentActivity {
  'recentProducts' : Array<Product>,
  'recentOrders' : Array<Order>,
}
export type Time = bigint;
export interface UserProfile {
  'contact' : string,
  'name' : string,
  'createdAt' : Time,
  'role' : UserRole,
  'suspended' : boolean,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'businessBuyer' : null } |
  { 'homeBuyer' : null } |
  { 'farmer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'ordersMade' : bigint,
  'ordersReceived' : bigint,
  'productsListed' : bigint,
}
export interface UserWithStats { 'stats' : UserStats, 'profile' : UserProfile }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'bulkUpdateProductAvailability' : ActorMethod<
    [Array<bigint>, boolean],
    undefined
  >,
  'createProduct' : ActorMethod<
    [
      string,
      string,
      ProductCategory,
      number,
      bigint,
      ProductUnit,
      boolean,
      [] | [ExternalBlob],
    ],
    Product
  >,
  'createProfile' : ActorMethod<
    [string, string, string, UserRole],
    UserProfile
  >,
  'deleteProduct' : ActorMethod<[bigint], Product>,
  'deleteUserAccount' : ActorMethod<[Principal], undefined>,
  'getAllActiveUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllSuspendedUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAllUsersWithStats' : ActorMethod<[], Array<UserWithStats>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getFarmerOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getPlatformAnalytics' : ActorMethod<[], PlatformAnalytics>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getProductsByFarmer' : ActorMethod<[Principal], Array<Product>>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getRecentActivity' : ActorMethod<[], RecentActivity>,
  'getTotalActiveUsers' : ActorMethod<[], bigint>,
  'getTotalSuspendedUsers' : ActorMethod<[], bigint>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'getUserStats' : ActorMethod<[Principal], UserStats>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'moderateProduct' : ActorMethod<[bigint, boolean, [] | [string]], Product>,
  'placeOrder' : ActorMethod<[Array<OrderItem>, Principal], Order>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSuspendedProfile' : ActorMethod<[Principal, boolean], undefined>,
  'setUserRoleProfile' : ActorMethod<[Principal, UserRole], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      string,
      ProductCategory,
      number,
      bigint,
      ProductUnit,
      boolean,
      [] | [ExternalBlob],
    ],
    Product
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];