/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductCategory = IDL.Variant({
  'grains' : IDL.Null,
  'organicFood' : IDL.Null,
  'others' : IDL.Null,
  'fruits' : IDL.Null,
  'vegetables' : IDL.Null,
  'dairy' : IDL.Null,
});
export const ProductUnit = IDL.Variant({
  'kg' : IDL.Null,
  'pieces' : IDL.Null,
  'liters' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'imageBlob' : IDL.Opt(ExternalBlob),
  'organic' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'unit' : ProductUnit,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'quantity' : IDL.Nat,
  'category' : ProductCategory,
  'price' : IDL.Float64,
  'farmer' : IDL.Principal,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'businessBuyer' : IDL.Null,
  'homeBuyer' : IDL.Null,
  'farmer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'location' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'fulfilled' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'createdAt' : Time,
  'totalAmount' : IDL.Float64,
  'buyer' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
  'farmer' : IDL.Principal,
});
export const PlatformAnalytics = IDL.Record({
  'totalProducts' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'totalHomeBuyers' : IDL.Nat,
  'totalBusinessBuyers' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
  'totalFarmers' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ProductCategory,
        IDL.Float64,
        IDL.Nat,
        ProductUnit,
        IDL.Bool,
        IDL.Opt(ExternalBlob),
      ],
      [Product],
      [],
    ),
  'createProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, UserRole],
      [UserProfile],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [Product], []),
  'deleteUserAccount' : IDL.Func([IDL.Principal], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getFarmerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getPlatformAnalytics' : IDL.Func([], [PlatformAnalytics], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsByFarmer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'moderateProduct' : IDL.Func([IDL.Nat, IDL.Bool], [Product], []),
  'placeOrder' : IDL.Func([IDL.Vec(OrderItem), IDL.Principal], [Order], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        ProductCategory,
        IDL.Float64,
        IDL.Nat,
        ProductUnit,
        IDL.Bool,
        IDL.Opt(ExternalBlob),
      ],
      [Product],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductCategory = IDL.Variant({
    'grains' : IDL.Null,
    'organicFood' : IDL.Null,
    'others' : IDL.Null,
    'fruits' : IDL.Null,
    'vegetables' : IDL.Null,
    'dairy' : IDL.Null,
  });
  const ProductUnit = IDL.Variant({
    'kg' : IDL.Null,
    'pieces' : IDL.Null,
    'liters' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'imageBlob' : IDL.Opt(ExternalBlob),
    'organic' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'unit' : ProductUnit,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'quantity' : IDL.Nat,
    'category' : ProductCategory,
    'price' : IDL.Float64,
    'farmer' : IDL.Principal,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'businessBuyer' : IDL.Null,
    'homeBuyer' : IDL.Null,
    'farmer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'location' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'fulfilled' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'createdAt' : Time,
    'totalAmount' : IDL.Float64,
    'buyer' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
    'farmer' : IDL.Principal,
  });
  const PlatformAnalytics = IDL.Record({
    'totalProducts' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'totalHomeBuyers' : IDL.Nat,
    'totalBusinessBuyers' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
    'totalFarmers' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ProductCategory,
          IDL.Float64,
          IDL.Nat,
          ProductUnit,
          IDL.Bool,
          IDL.Opt(ExternalBlob),
        ],
        [Product],
        [],
      ),
    'createProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, UserRole],
        [UserProfile],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [Product], []),
    'deleteUserAccount' : IDL.Func([IDL.Principal], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getFarmerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getPlatformAnalytics' : IDL.Func([], [PlatformAnalytics], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByFarmer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'moderateProduct' : IDL.Func([IDL.Nat, IDL.Bool], [Product], []),
    'placeOrder' : IDL.Func([IDL.Vec(OrderItem), IDL.Principal], [Order], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          ProductCategory,
          IDL.Float64,
          IDL.Nat,
          ProductUnit,
          IDL.Bool,
          IDL.Opt(ExternalBlob),
        ],
        [Product],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };